# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.2.0.schema.json

PackageIdentifier: MinnekDigitalStudio.Cominnek
PackageVersion: 2.0.0-alpha.2
Installers:
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://github.com/Minnek-Digital-Studio/cominnek/releases/download/v2.0.0-alpha.2/cominnek_2.0.0-alpha.2.exe
  InstallerSha256: 6695685720437228A3A852713D7CFF0DB998372FE712E3B123C82F135495E0CF
ManifestType: installer
ManifestVersion: 1.2.0

