# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: MinnekDigitalStudio.Cominnek
PackageVersion: 2.0.0-alpha.2
PackageLocale: en-US
Publisher: Minnek Digital Studio
PackageName: cominnek
License: GNU
ShortDescription: Create commits & pull requests in an easy way
ManifestType: defaultLocale
ManifestVersion: 1.2.0

